### ISSUE TITLE
please provide instructions to run simulation

### ISSUE THREAD

**Issue by kumavis** [ethereum/economic-modeling#3]
I am not a pythonista. not sure what to do.

```
╭─kumavis@xyzs-MBP  ~/dev/eth-economic-modeling/casper3   (master*) 
╰─$ python test.py 
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from casper import Validator
  File "/Users/kumavis/dev/eth-economic-modeling/casper3/casper.py", line 1, in <module>
    from ethereum.casper_utils import RandaoManager, get_skips_and_block_making_time, \
ImportError: No module named ethereum.casper_utils
```

```
╭─kumavis@xyzs-MBP  ~/dev/eth-economic-modeling/casper3   (master*) 
╰─$ python --version
Python 2.7.11
```

**Comment by cryptophonic** [comment]
did this ever get answered?  same problem here.

**Comment by janx** [comment]
Run it with https://github.com/ethereum/pyethereum/commit/e8a4f7c.

**Comment by cryptophonic** [comment]
awesome, thanks for the input.  will give that a shot.

**Comment by cryptophonic** [comment]
Following up on this, the commit above (e8a4f7c) worked for me against the tip for this repo as of today.  @kumavis set your PYTHONPATH to the pyethereum repo directory after cloning that rev and it should work.
